#!/usr/bin/env ruby

#
# Android Cluster Toolkit
#
# mbb - execute a command on the selected device(s) using busybox
#
# (c) 2012-2015 Joshua J. Drake (jduck)
#

bfn = __FILE__
while File.symlink?(bfn)
  bfn = File.expand_path(File.readlink(bfn), File.dirname(bfn))
end
$:.unshift(File.join(File.dirname(bfn), 'lib'))


require 'devices'
load_connected(false)

require 'madb'


# process args
if not parse_global_options() or ARGV.length < 1
  $stderr.puts "usage: mbb [-1v] -d <device names or serials separated by commas> <parameters to busybox>"
  exit(1)
end


# run the commands
multi_adb(['shell', '/data/local/tmp/busybox'])
