#!/usr/bin/env ruby

#
# Android Cluster Toolkit
#
# mpull - pull a path from the selected device(s)
#
# (c) 2012-2014 Joshua J. Drake (jduck)
#

bfn = __FILE__
while File.symlink?(bfn)
  bfn = File.expand_path(File.readlink(bfn), File.dirname(bfn))
end
$:.unshift(File.dirname(bfn))

require 'devices'
require 'madb'


# process args
if ARGV.length < 2 or not parse_global_options()
  $stderr.puts "usage: mpull [-1v] -d <device names or serials separated by commas> <path to pull>"
  exit(1)
end

path = ARGV.shift


#
# NOTE: this can't use multi_adb because it has a device-dependant argument
#
$devices.each { |dev|

  next if not is_selected(dev)

  if dev[:disabled]
    puts "[!] Warning: The selected device is marked disabled. It may not be present."
  end

  print_col_prefix(dev)
  
  cmd = [ 'adb', '-s', dev[:serial], 'pull' ]
  cmd << path
  cmd << File.join([ 'devices', dev[:name], path ])
  #puts cmd
  system(*cmd)

  puts "" if not $one_line
}
